### ISSUE TITLE
Unsaved changes on note view

### ISSUE THREAD

**Issue by Klaustrix** [SankethBK/diaryvault#209]
Not sure if this is still being worked on, great app, but some small UX annoyances.

When I tap a note and view it, then try to go back it pops up a 'you have unsaved changes' notification.

I haven't done anything to the note, and this makes trying to review multiple notes quickly very tedious.

**Comment by SankethBK** [comment]
Hi, thanks for raising, I will consider it for next release

**Comment by zdoryyk** [comment]
Hi, I would like to take this task if that possible, can I try?

**Comment by SankethBK** [comment]
Hi @zdoryyk , you can definitely try it. It's bit tricky because `NoteInitialState` is the initial state and `controller` parameter holds the rich text editor's internal state. It will only be transitioned to `NoteUpdatedState` when `title`, `createdAt`, `allNoteAssets` or `tags` is updated, but if user types something into rich text editor without changing any of these, the state will still be `NoteInitialState` as controller takes care of managing rich text editor's state internally. 

Few solutions i can think is to subscribe to some listener exposed by rich text editor's controller for state changes. Although i am not sure if such a stream exists.

**Comment by SankethBK** [comment]
Or a much cleaner approach would be when user clicks on back button we can check diff between current note state and original note from DB and decide whether to show the popup.

**Comment by zdoryyk** [comment]
@SankethBK ty very much, I'll try it, if i have problem, can i contact you, I have never had experience with this big application, its will be ok?

**Comment by SankethBK** [comment]
Yes sure, feel free to ask for help, you can join our discord server as well (link in readme).

**Comment by zdoryyk** [comment]
@SankethBK Sorry, I didnt have time for it, I would like to get a new not too hard task, can I?
