### ISSUE TITLE
Save Note not working after delete. 

### ISSUE THREAD

**Issue by droidbg** [SankethBK/diaryvault#38]
## Describe the bug
Whenever you delete all the notes and then create a new note and try to save it, you will get toast of "Note saved successfully" but the note will not be visible in home page.

## To Reproduce
1. Create 1 or more notes in home page.
2. Delete all notes
3. Create one more new note, and save it. 
You will be able to reproduce this. 

## Expected behavior
New Saved Note should be visible in home page

## Screenshots/Video

https://github.com/SankethBK/diaryvault/assets/41873024/5ce80293-d9a3-4e5b-b89b-c46e89c7a63d

**Comment by SankethBK** [comment]
This issue was introduced in this [PR](https://github.com/SankethBK/diaryvault/pull/12)

When we delete a note, instead of deleting the record for that Note in db, we set all of its attributes to `null` and set `deleted` as 1, because we need to delete same note_id in cloud as well

```
      // update table by setting all fields of note to null, except id, last modified
      count = await database.update(
          Notes.TABLE_NAME,
          {
            "title": null,
            "body": null,
            "plain_text": null,
            "created_at": null,
            "hash": null,
            "last_modified": DateTime.now().millisecondsSinceEpoch,
            "deleted": 1,
          },
          where: "${Notes.ID} = ?",
          whereArgs: [id]);
```

The issue here arises from `fetchNotesPreview` function in `lib/features/notes/data/datasources/local data sources/local_data_source.dart`

```
@override
  Future<List<NotePreviewModel>> fetchNotesPreview(String authorId) async {
    // Only columns required for notes preview
    List<Map<String, Object?>> result;
    try {
      result = await database.query(Notes.TABLE_NAME,
          columns: [Notes.ID, Notes.TITLE, Notes.PLAIN_TEXT, Notes.CREATED_AT],
          where:
              "${Notes.DELETED} != 1 and ${Notes.AUTHOR_ID} = '$authorId' or ${Notes.AUTHOR_ID} = '${GuestUserDetails.guestUserId}'",
          orderBy: "${Notes.CREATED_AT} DESC");
    } catch (e) {
      log.e("Local database query for fetching notes preview failed $e");
      throw const DatabaseQueryException();
    }

    return result.map((noteMap) => NotePreviewModel.fromJson(noteMap)).toList();
  }
```

The query here used to fetch the notes here is wrong. The query running currently is 
```SELECT id, title, plain_text, created_at FROM Notes WHERE deleted != 1 and author_id = '17d8af20-6054-11ee-be82-b1b190fc05e2' or author_id = 'guest_user_id' ORDER BY created_at DESC'```

This will select the notes even for which `deleted` is set to 1, because the operator precedence is wrong. The actual query should have been  (added brackets around author_id condition for precendency.
```SELECT id, title, plain_text, created_at FROM Notes WHERE deleted != 1 and (author_id = '17d8af20-6054-11ee-be82-b1b190fc05e2' or author_id = 'guest_user_id') ORDER BY created_at DESC'```


The same mistake is there at 4-5 places in `NotesLocalDataSource`

**Comment by droidbg** [comment]
@SankethBK I will fix this, could you assign it to me.

**Comment by SankethBK** [comment]
Sure @droidbg
